name: WAMP Dart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.4.0

      - name: Install dependencies
        run: make install

      - name: Verify formatting
        run: make check-format

      - name: Check lint
        run: make lint

      - name: Setup AAT
        run: |
          git clone https://github.com/xconnio/xconn-aat-setup.git
          cd xconn-aat-setup
          make build-docker-nxt
          make build-docker-crossbar
          docker compose up -d

      - name: Run tests
        run: make tests
